<?php

return array (
  'APP_NAME' => 'AetherPanel',
  'APP_ENV' => 'production',
  'APP_DEBUG' => true,
  'APP_URL' => 'http://localhost:8080',
  'PANEL_FRONTEND_URL' => 'http://localhost:3000',
  'APP_TIMEZONE' => 'UTC',
  'APP_LOCALE' => 'en',
  'APP_FALLBACK_LOCALE' => 'en',
  'APP_KEY' => 'base64:X364Xx1XX1P0Q8xvyasgZvF+9IrdK+MC0e2E7+++vDQ=',
  'FRONTEND_API_KEY' => 'local-aetherpanel-frontend-key',
  'APP_SERVICE_AUTHOR' => 'noreply@panel.example.com',
  'APP_CORS_ALLOWED_ORIGINS' => 
  array (
    0 => 'http://localhost:3000',
  ),
  'PTERODACTYL_CDN_ENABLED' => false,
  'PTERODACTYL_CDN_CACHE_TIME' => 60,
  'GUZZLE_TIMEOUT' => 5,
  'GUZZLE_CONNECT_TIMEOUT' => 2,
  'FLASH_THEME_VERSION_CHECK_ENABLED' => false,
  'FLASH_THEME_HTTP_TIMEOUT' => 3,
  'FLASH_THEME_CONNECT_TIMEOUT' => 2,
  'SESSION_DRIVER' => 'cookie',
  'CACHE_DRIVER' => 'array',
  'QUEUE_CONNECTION' => 'sync',
  'SESSION_COOKIE' => 'aetherpanel_session',
  'SESSION_DOMAIN' => NULL,
  'SESSION_SECURE_COOKIE' => false,
  'SESSION_SAME_SITE' => 'lax',
  'SANCTUM_STATEFUL_DOMAINS' => 
  array (
    0 => 'localhost:3000',
    1 => 'localhost:8080',
  ),
  'DB_HOST' => '127.0.0.1',
  'DB_PORT' => '3306',
  'DB_DATABASE' => 'aeth',
  'DB_USERNAME' => 'aeth',
  'DB_PASSWORD' => 'your_password',
  'REDIS_HOST' => '127.0.0.1',
  'REDIS_PORT' => '6379',
  'REDIS_PASSWORD' => NULL,
  'MAIL_MAILER' => 'log',
  'MAIL_HOST' => '127.0.0.1',
  'MAIL_PORT' => '2525',
  'MAIL_USERNAME' => NULL,
  'MAIL_PASSWORD' => NULL,
  'MAIL_ENCRYPTION' => 'tls',
  'MAIL_FROM_ADDRESS' => 'noreply@panel.example.com',
  'MAIL_FROM_NAME' => 'AetherPanel',
  'RECAPTCHA_ENABLED' => false,
  'RECAPTCHA_SECRET_KEY' => '',
  'RECAPTCHA_WEBSITE_KEY' => '',
);
